### ISSUE TITLE
test.py occurred FileNotFoundError

### ISSUE THREAD

**Issue by yzj2019** [CVMI-Lab/PLA#12]
Thanks for this siginificant and interesting work.
I'm running inference code following your guidance, but occurred FileNotFoundError when running test.py, and i don't know how to fix it.
```
=> loaded text embedding from path '../data/scannetv2/text_embed/scannet_clip-ViT-B16_id.pth'
Traceback (most recent call last):
  File "test.py", line 236, in <module>
    main()
  File "test.py", line 232, in main
    eval_output_dir=eval_output_dir)
  File "test.py", line 61, in eval_single_ckpt
    epoch_id = model.load_params_from_file(filename=args.ckpt, logger=logger, epoch_id=epoch_id, to_cpu=dist_test)
  File "/workspace/PLA/pcseg/models/vision_networks/network_template.py", line 200, in load_params_from_file
    raise FileNotFoundError
FileNotFoundError
```
All error information is in the attached file.
[err-230614.log](https://github.com/CVMI-Lab/PLA/files/11744144/err-230614.log)

**Comment by yzj2019** [comment]
I've down all the preparation following `INSTALL.md` and `DATASET.md`

**Comment by Dingry** [comment]
Hi, this error occurs mostly due to the wrong checkpoint path. Could you please check whether the input ckpt exists?

**Comment by yzj2019** [comment]
> Hi, this error occurs mostly due to the wrong checkpoint path. Could you please check whether the input ckpt exists?

I'm sure that the ckpt exists. I think maybe due to the relative path in the code.
